### ISSUE TITLE
whats the suggested handling if user forgot their PIN?

### ISSUE THREAD

**Issue by thiendangvan** [Portkey-Wallet/react-native-sdk#116]
Currently, the SDK supports to disconnect the wallet when the wallet status is unlocked (already verify PIN code). so in the case that user forgot their PIN, they cannot disconnect or change wallet. so do you have any suggestions for situations where the user has forgotten their PIN?

**Comment by wade-portkey** [comment]
> Currently, the SDK supports to disconnect the wallet when the wallet status is unlocked (already verify PIN code). so in the case that user forgot their PIN, they cannot disconnect or change wallet. so do you have any suggestions for situations where the user has forgotten their PIN?

hi @thiendangvan , Currently, after forgetting the PIN code, users can only delete the app and then reinstall it in order to continue using it. If needed, we can add an API so that users can reconnect their wallets after forgetting the PIN code.

**Comment by thiendangvan** [comment]
hi @wade-portkey, Can you describe more about this?
>  we can add an API so that users can reconnect their wallets after forgetting the PIN code.

btw, is it feasible to add an API to clear local wallet data? so we can add a button for user to reset data on their device

**Comment by wade-portkey** [comment]
> hi @wade-portkey, Can you describe more about this?
> 
> > we can add an API so that users can reconnect their wallets after forgetting the PIN code.
> 
> btw, is it feasible to add an API to clear local wallet data? so we can add a button for user to reset data on their device

hi, @thiendangvan ,

If a user forgets the PIN code, the user loses their private key and cannot continue using the wallet. 

We can add an API that allows users to reconnect to the wallet after forgetting the PIN code. In this case, the user needs to go through the social recovery process again, this will generate a new private key, and the user will regain control of the wallet. (However, this feature needs to be used carefully because the portkey has a maximum device limit. The maximum number of devices allowed by portkey for login is 70. If a user frequently forgets the PIN code and reconnects to the wallet, after exceeding 70 attempts, they will no longer be able to log in again. )

We can also add an API to clear local wallet data, which is similar to reconnecting to the wallet after forgetting the PIN code as mentioned above.

**Comment by thiendangvan** [comment]
> We can add an API that allows users to reconnect to the wallet after forgetting the PIN code. In this case, the user needs to go through the social recovery process again, this will generate a new private key, and the user will regain control of the wallet. (However, this feature needs to be used carefully because the portkey has a maximum device limit. The maximum number of devices allowed by portkey for login is 70. If a user frequently forgets the PIN code and reconnects to the wallet, after exceeding 70 attempts, they will no longer be able to log in again. )
> 
> We can also add an API to clear local wallet data, which is similar to reconnecting to the wallet after forgetting the PIN code as mentioned above.

thanks for your information, we have noted this and will take this in mind, your team dun need to implement it for now
